export type Card = {
  id: string;
  oracle_id?: string;
  name: string;
  type_line?: string;
  oracle_text?: string;
  mana_cost?: string;
  colors?: string[];
  color_identity: string[];
  keywords?: string[];
  produced_mana: string[];
  power?: string;
  toughness?: string;
  cmc?: number;
  set?: string;
  set_name?: string;
  rarity?: string;
  image_uris?: {
    small?: string;
    normal?: string;
    art_crop?: string;
  };
  artist?: string;
  released_at?: string;
  layout?: string;
  games?: string[];
  lang?: string;
  digital?: boolean;
  flavor_text?: string;
  legalities?: Record<string, string>;
  game_changer: boolean;
};
